CREATE TABLE `QUOKI_USER` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(100) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
);

INSERT INTO `QUOKI_USER` VALUES(1, 'alice', 's3cr3t');